---
# tasks file for prod
- name: Ensure tomcat package is present
  apt:
    name: tomcat8
    state: present

- name: Ensure tomcat servise is started
  service:
    name: tomcat8
    state: started

- name: Ensure Puzzle15-1.0-SNAPSHOT present in directory
  copy: src=/srv/puzzle15/target/Puzzle15-1.0-SNAPSHOT.war dest=/var/lib/tomcat8/webapps/Puzzle15-1.0-SNAPSHOT.war
  notify:
    - restart tomcat
